{
 "title": "Batch",
 "time": { "from": "2019-01-26T16:53:46.000Z", "to": "2019-01-26T16:59:13.000Z" },
 "panels": [
  {
   "title": "Share of requests by HTTP request type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT method, count(method) FROM parsed GROUP BY method;"
    }
   ]
  },
  {
   "title": "Top 5 most common IP addresses of requests ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT remote_addr, count(remote_addr) FROM parsed GROUP BY remote_addr ORDER BY count DESC LIMIT 5;"
    }
   ]
  },
  {
   "title": "Bytes sent by server across time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "select time_local, sum(body_bytes_sent) from parsed GROUP BY time_local;"
    }
   ]
  }
 ]
}