{
 "title": "Streams",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Average request processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select new_timestamp, avg(request_processing_time) from streams GROUP BY new_timestamp;"
    }
   ]
  },
  {
   "title": "Share of requests by HTTP request type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT request_method, count(request_method) FROM streams GROUP BY request_method;"
    }
   ]
  },
  {
   "title": "Total sent bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select new_timestamp, sum(sent_bytes) from streams GROUP BY new_timestamp;\n-- select * from streams ;"
    }
   ]
  }
 ]
}