apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432
    isDefault: true
    user: postgres
    secureJsonData:
      password: pass
    jsonData:
      database: postgres
      sslMode: disable
